[package]
name = "pokebot-crystal"
version = "0.1.0"
authors = ["kixelated <kixelated@gmail.com>"]
links = "z"

[dependencies]
libc = "0.2.0"

[dependencies.sdl2]
version = "0.30.0"
features = ["gfx"]
